export const stripePaymentTypes = {
    PAYMENT_SUCCESS : "PAYMENT_SUCCESS",
    PAYMENT_FAIL : "PAYMENT_FAIL",
    PAYMENT : "PAYMENT",

    GET_PAYMENT_SUCCESS : "GET_PAYMENT_SUCCESS",
    GET_PAYMENT_FAIL : "GET_PAYMENT_FAIL",
    GET_PAYMENT : "GET_PAYMENT",
};