export const CartTypes = {
    ADD_CART_REQUEST: "ADD_CART_REQUEST",
    ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
    ADD_CART_FAIL: "ADD_CART_FAIL",

    GET_CART_REQUEST: "GET_CART_REQUEST",
    GET_CART_SUCCESS: "GET_CART_SUCCESS",
    GET_CART_FAIL: "GET_CART_FAIL",

    UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    UPDATE_CART_FAIL: "UPDATE_CART_FAIL",

    DELETE_CART_REQUEST: "DELETE_CART_REQUEST",
    DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",
    DELETE_CART_FAIL: "DELETE_CART_FAIL",
};
