export const categoryProductTypes = {
    GET_CATEGORY_PRODUCT_SUCCESS : "GET_CATEGORY_PRODUCT_SUCCESS",
    GET_CATEGORY_PRODUCT_FAIL : "GET_CATEGORY_PRODUCT_FAIL",
    GET_CATEGORY_PRODUCT : "GET_CATEGORY_PRODUCT",
};