export const orderTypes = {
    GET_PAYMENT_SUCCESS : "GET_PAYMENT_SUCCESS",
    GET_PAYMENT_FAIL : "GET_PAYMENT_FAIL",
    GET_ORDER_SUCCESS : "GET_ORDER_SUCCESS",
    GET_ORDER_FAIL : "GET_ORDER_FAIL",
    GET_ORDER : "GET_ORDER",
};