export const profileTypes = {
    GET_PROFILE_SUCCESS : "GET_PROFILE_SUCCESS",
    GET_PROFILE_FAIL : "GET_PROFILE_FAIL",
    GET_PROFILE : "GET_PROFILE",

    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAIL : "LOGOUT_FAIL",
    LOGOUT : "LOGOUT",
};